### ISSUE TITLE
unable to troubleshoot extension on localhost:3000

### ISSUE THREAD

**Issue by jeremyd** [toastr-space/keys-band#10]
When I try to debug my application using this extension locally, chrome denies loading the extension with the following error: 

```
localhost/:1 Denying load of chrome-extension://jdencabhccnfhedpfoojbbdlgmecnlkm/build/nostr-provider.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
content.js:25     GET chrome-extension://invalid/ net::ERR_FAILED
```

This does not happen with nos2x.  Do you know what the issue might be?

**Comment by satoshisound** [comment]
I haven't seen this on my end. Which browser are you using? Do you have the extensions set to developer mode?

**Comment by jeremyd** [comment]
Ah, to clarify, i was attempting to debug my application, on localhost:3000, with the release of the extension from the regular channel.  When I ran the extension in developer mode from a source checkout it did work..

I think this may not be a bug, just a difference from nos2x.. I am still learning how developing for extensions works.  Closing this.
